/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from '../../common';

export interface UwUUiPriceGetterInterface extends utils.Interface {
  functions: {
    'ethAggregator()': FunctionFragment;
    'getPrice()': FunctionFragment;
    'uwuLp()': FunctionFragment;
    'uwuToken()': FunctionFragment;
    'wethToken()': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: 'ethAggregator' | 'getPrice' | 'uwuLp' | 'uwuToken' | 'wethToken'
  ): FunctionFragment;

  encodeFunctionData(functionFragment: 'ethAggregator', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getPrice', values?: undefined): string;
  encodeFunctionData(functionFragment: 'uwuLp', values?: undefined): string;
  encodeFunctionData(functionFragment: 'uwuToken', values?: undefined): string;
  encodeFunctionData(functionFragment: 'wethToken', values?: undefined): string;

  decodeFunctionResult(functionFragment: 'ethAggregator', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getPrice', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'uwuLp', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'uwuToken', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'wethToken', data: BytesLike): Result;

  events: {};
}

export interface UwUUiPriceGetter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: UwUUiPriceGetterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ethAggregator(overrides?: CallOverrides): Promise<[string]>;

    getPrice(overrides?: CallOverrides): Promise<[BigNumber] & { price: BigNumber }>;

    uwuLp(overrides?: CallOverrides): Promise<[string]>;

    uwuToken(overrides?: CallOverrides): Promise<[string]>;

    wethToken(overrides?: CallOverrides): Promise<[string]>;
  };

  ethAggregator(overrides?: CallOverrides): Promise<string>;

  getPrice(overrides?: CallOverrides): Promise<BigNumber>;

  uwuLp(overrides?: CallOverrides): Promise<string>;

  uwuToken(overrides?: CallOverrides): Promise<string>;

  wethToken(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    ethAggregator(overrides?: CallOverrides): Promise<string>;

    getPrice(overrides?: CallOverrides): Promise<BigNumber>;

    uwuLp(overrides?: CallOverrides): Promise<string>;

    uwuToken(overrides?: CallOverrides): Promise<string>;

    wethToken(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    ethAggregator(overrides?: CallOverrides): Promise<BigNumber>;

    getPrice(overrides?: CallOverrides): Promise<BigNumber>;

    uwuLp(overrides?: CallOverrides): Promise<BigNumber>;

    uwuToken(overrides?: CallOverrides): Promise<BigNumber>;

    wethToken(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    ethAggregator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    uwuLp(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    uwuToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    wethToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
