#!/bin/bash  --save
npm remove @myetherwallet/mewconnect-web-client --save
npm remove @pmmmwh/react-refresh-webpack-plugin --save
npm remove @svgr/webpack --save
npm remove @types/react-custom-scrollbars --save
npm remove @types/react-modal --save
npm remove @visx/axis --save
npm remove @visx/curve --save
npm remove @visx/grid --save
npm remove @visx/scale --save
npm remove @web3-react/portis-connector --save
npm remove babel-jest --save
npm remove babel-loader --save
npm remove babel-plugin-named-asset-import --save
npm remove babel-preset-react-app --save
npm remove bfj --save
npm remove camelcase --save
npm remove case-sensitive-paths-webpack-plugin --save
npm remove css-loader --save
npm remove d3-array --save
npm remove dotenv --save
npm remove dotenv-expand --save
npm remove eslint-config-react-app --save
npm remove eslint-webpack-plugin --save
npm remove front-matter --save
npm remove fs-extra --save
npm remove graphql-ws --save
npm remove html-webpack-plugin --save
npm remove identity-obj-proxy --save
npm remove intl --save
npm remove jest-circus --save
npm remove jest-resolve --save
npm remove jest-watch-typeahead --save
npm remove mini-css-extract-plugin --save
npm remove optimize-css-assets-webpack-plugin --save
npm remove paraswap --save
npm remove pnp-webpack-plugin --save
npm remove postcss-flexbugs-fixes --save
npm remove postcss-loader --save
npm remove postcss-normalize --save
npm remove postcss-preset-env --save
npm remove postcss-safe-parser --save
npm remove prompts --save
npm remove react-dev-utils --save
npm remove react-markdown --save
npm remove react-scripts --save
npm remove react-share --save
npm remove reflect-metadata --save
npm remove resolve --save
npm remove resolve-url-loader --save
npm remove sass-loader --save
npm remove semver --save
npm remove serve --save
npm remove style-loader --save
npm remove terser-webpack-plugin --save
npm remove ts-pnp --save
npm remove tsparticles --save
npm remove url-loader --save
npm remove webpack-manifest-plugin --save
npm remove workbox-webpack-plugin --save
