/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from './interfaces';
export type { interfaces };
import type * as solmate from './solmate';
export type { solmate };
export type { YoSifuStargateVault } from './YoSifuStargateVault';
export type { YoSifuStargateVaultWrapper } from './YoSifuStargateVaultWrapper';
