/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from './interfaces';
export type { interfaces };
import type * as layerzerolabs from './layerzerolabs';
export type { layerzerolabs };
export type { LPStaking } from './LPStaking';
export type { LPTokenERC20 } from './LPTokenERC20';
export type { OmnichainFungibleToken } from './OmnichainFungibleToken';
export type { Pool } from './Pool';
export type { StargateToken } from './StargateToken';
